# Generated by Django 3.0.5 on 2020-04-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_auto_20200414_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookApp.Customer'),
            preserve_default=False,
        ),
    ]
